version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ast-db
    environment:
      POSTGRES_USER: asterisk
      POSTGRES_PASSWORD: asterisk
      POSTGRES_DB: asterisk
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data

  asterisk:
    image: asterisk-normal:22.5.1
    container_name: asterisk
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "5060:5060/udp"     # SIP UDP
      - "5060:5060/tcp"     # SIP TCP
      - "8089:8089/tcp"     # WebSocket Secure (WebRTC)
      - "10000-10100:10000-10100/udp"  # RTP para audio/video (ajustar rango seg√∫n necesidad)
    
volumes:
  dbdata:
